WebApplication/Controllers/RegisterController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.BusinessLogic.DbModel.Seed;
using WebApplication.Domain.Entities.User;
using WebApplication.Helper;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class RegisterController : BaseController
    {
        [HttpPost]
        public ActionResult Index(userRegister register)
        {
            URegisterResp reg = new URegisterResp();
            if (ModelState.IsValid)
            {
                register.Password = LoginHelper.HashGen(register.Password);
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<userRegister, UDbTable>();
                });

                IMapper iMapper = config.CreateMapper();
                var localProd = iMapper.Map<userRegister, UDbTable>(register);
                localProd.Level = 0;
                localProd.lastLogin = DateTime.Now;
                localProd.UserIp = Request.UserHostAddress;
                using (UserContext prod = new UserContext())
                {
                    prod.Users.Add(localProd);
                    prod.SaveChanges();
                }
            }
            else
            {
                ModelState.AddModelError("Parolele nu coincid!", reg.StatusMessage);
                return View();
            }
            return RedirectToAction("Index", "Login");
        }

        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication/Views/Register/Index.cshtml
@model WebApplication.Models.userRegister

@{
    Layout = "~/Views/Shared/_RegisterLayout.cshtml";
    ViewBag.Title = "Register Page";
}


<div class="page-content">
    <div class="form-v5-content">
        @using (Html.BeginForm("Index", "Register", FormMethod.Post, new { @class = "form-detail"}))
        {
            <h2>Register Account Form</h2>
            <div class="form-row">
                @Html.LabelFor(m => m.Username, new { @for = "full-name" })
                @Html.TextBoxFor(m => m.Username, new
               {
                   placeholder = "Numele de utilizator",
                   name = "full-name",
                   id = "full-name",
                   @class = "input-text",
                   type = "text",
                   autocomplete = "off"
               })
                <i class="fas fa-user"></i>
            </div>
            <div class="form-row">
                @Html.LabelFor(m => m.Email, new { @for = "your-email" })
                @Html.TextBoxFor(m => m.Email, new
                   {
                       placeholder = "Email",
                       name = "your-email",
                       id = "your-email",
                       @class = "input-text",
                       type = "text",
                       required = true,
                       pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}",
                       autocomplete = "off"
                   })
                <i class="fas fa-envelope"></i>
            </div>
            <div class="form-row">
                @Html.LabelFor(m => m.Password, new { @for = "password" })
                @Html.TextBoxFor(m => m.Password, new
                   {
                       placeholder = "**********",
                       name = "password",
                       id = "password",
                       @class = "input-text",
                       type = "password",
                       required = true,
                       autocomplete = "off"
                   })
                <i class="fas fa-lock"></i>
            </div>
            <div class="form-row-last">
                <input type="submit" class="register">
            </div>
        }
    </div>
</div>