WebApplication/Controllers/ServiceController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using WebApplication.ActionFilter;
using WebApplication.BusinessLogic;
using WebApplication.BusinessLogic.Interface;
using WebApplication.Domain.Entities.Services;
using WebApplication.Domain.Entities.Staff;
using WebApplication.Domain.Entities.User;
using WebApplication.Models;
using WebApplication.Models.uData;

namespace WebApplication.Controllers
{
    public class ServiceController : BaseController
    {
        private readonly ISession _session;
        private readonly IService _service;// GET: Service
        public ServiceController()
        {
            BussinesLogic bl = new BussinesLogic();
            _service = bl.GetServiceBL();
            _session = bl.GetSessionBL();
        }

        [UserMod]
        public ActionResult Index()
        { 
            SessionStatus();
            if ((string)System.Web.HttpContext.Current.Session["LoginStatus"] != "login")
            {
                return RedirectToAction("Index", "Login");
            }

            UserMinimal userMin = null;
            List<userWorkers> uStaff = new List<userWorkers>();
            userData u = new userData();
            
            HttpCookie CookieApi = System.Web.HttpContext.Current.Request.Cookies["X-KEY"];
            if (CookieApi != null)
            {
                userMin = _session.GetUserByCookie(CookieApi.Value);
            }
            if (userMin == null)
            {
                u.Username = "Username";
            }
            else
            {
                u.Username = userMin.Username;
            }
            List<Service> serviceData = _service.GetServices();
            List<Worker> staffData = _service.GetStaff();
            foreach(var s in staffData)
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<Worker, userWorkers>();
                });

                IMapper iMapper = config.CreateMapper();
                var localStaff = iMapper.Map<Worker, userWorkers>(s);
                uStaff.Add(localStaff);
            }

            u.staff = uStaff;
            
            u.services = serviceData;

            return View(u);
        }

        public ActionResult ServiceDetail(int id)
        {
            UserMinimal user = new UserMinimal();
            userData u = new userData();
            List<Worker> Workers = new List<Worker>();
            u.staff = new List<userWorkers>();

            SessionStatus();
            if ((string)System.Web.HttpContext.Current.Session["LoginStatus"] != "login")
            {
                return RedirectToAction("Index", "Login");
            }
           
            HttpCookie CookieApi = System.Web.HttpContext.Current.Request.Cookies["X-KEY"];
            if (CookieApi != null)
            {
                user = _session.GetUserByCookie(CookieApi.Value);
            }
            if (user == null)
            {
                u.Username = "utilizator neautentificat";
            }
            else
            {
                u.Username = user.Username;
            }

            u.lastServices = _service.GetServices();
            u.service = _service.GetSingleService(id);
            u.services = _service.GetServices();

            Workers = _service.GetStaff();

            u.lastServices = u.lastServices.GetRange(0, 2);

            foreach (var employee in Workers)
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<Worker, userWorkers>();
                });

                IMapper iMapper = config.CreateMapper();
                var localStaff = iMapper.Map<Worker, userWorkers>(employee);
                u.staff.Add(localStaff);
            }

            return View(u);
        }
    }
}

WebApplication/Views/Service/Index.cshtml
@{ 
    Layout = "~/Views/Shared/_PageLayout.cshtml";
    ViewBag.Title = "Service Page";
}

@model WebApplication.Models.userData

<div class="section padding_layout_1 service_list">
    <div class="container">
        <div class="row">
            @{
                var service = Model.services;
                foreach (var s in service)
                {
                    <div class="col-md-4 service_blog margin_bottom_50">
                        <div class="full">
                            <div class="service_img"> <img class="img-responsive" src="@s.Image" alt="#" /> </div>
                            <div class="service_cont">
                                <h3 class="service_head">@s.Name</h3>
                                <p>@s.Description</p>
                                <div class="bt_cont"> @Html.ActionLink("View Service", "ServiceDetail", "Service", new { id = s.Id }, new { @class = "btn sqaure_bt" }) </div>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

WebApplication/Views/Service/ServiceDetail.cshtml
@{
    Layout = "~/Views/Shared/_PageLayout.cshtml";
    ViewBag.Title = "Detailed Service Page";
}

@model WebApplication.Models.userData

@{
    var service = Model.service;
    var services = Model.lastServices;
    var servicesList = Model.services;

    <div class="section padding_layout_1 service_list">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-12 service_blog margin_bottom_50">
                            <div class="full">
                                <div class="service_img"> <img class="img-responsive" src="@service.Image" alt="#" /> </div>
                                <div class="service_cont">
                                    <h3 class="service_head">@service.Name</h3>
                                    <p>
                                        @service.Description
                                    </p>
                                </div>
                            </div>
                        </div>
                        @{
                            foreach (var s in services)
                            {
                                <div class="col-md-6 service_blog margin_bottom_50">
                                    <div class="full">
                                        <div class="service_img"> <img class="img-responsive" src="@s.Image" alt="#" /> </div>
                                        <div class="service_cont">
                                            <h3 class="service_head">@s.Name</h3>
                                            <p>@s.Description</p>
                                            <div class="bt_cont"> @Html.ActionLink("View Service", "ServiceDetail", "Service", new { id = s.Id }, new { @class = "btn sqaure_bt" }) </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
                    
                </div>
                <div class="col-md-3">
                    <div class="side_bar">
                        <div class="side_bar_blog">
                            <h4>SEARCH</h4>
                            <div class="side_bar_search">
                                <div class="input-group stylish-input-group">
                                    <input class="form-control" placeholder="Search" type="text">
                                    <span class="input-group-addon">
                                        <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="side_bar_blog">
                            <h4>OUR SERVICE</h4>
                            <div class="categary">
                                <ul>
                                    @{
                                        foreach (var serv in servicesList)
                                        {
                                            <li><a href="/Service/ServiceDetail/@serv.Id"><i class="fa fa-angle-right"></i>@serv.Name</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}